enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 384
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 12.0
leavesCullingMode = "FAST"
leavesCullingAmount = 2
includeMangroveRoots = false
powderSnowCulling = true
entityModelCulling = false
useOnModdedBlocksByDefault = true

[modCompatibility]
bountiful = true
travelersbackpack = true
betterfurnacesreforged = true
waystones = true
advancednetherite = true
friendsandfoes = true
minecraft = true
