name: Build Modpack

on:
  push:
    branches:
      - 1.20.1
  workflow_dispatch:

jobs:
  Build-Modpack:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
          
      - run: git config user.email "${{ github.actor }}@users.noreply.github.com"
        if: ${{ github.repository_owner != 'github-actions' }}

      - run: git config user.name "${{ github.actor }}"
        if: ${{ github.repository_owner != 'github-actions' }}   
        
      - name: Set Timezone
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Asia/Shanghai"
          timezoneWindows: "China Standard Time"
          timezoneMacos: "Asia/Shanghai"
        
      - name: Get current date and time
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M')"
      
      - name: Build Standard Modpack
        run: |
          rm -rf .github
          rm -rf .git
          rm README.md
          cd overrides
          mv h.txt options.txt
          cd ..
          cd /home/runner/work/MineOptimiz/MineOptimiz/
          zip -r /home/runner/work/MineOptimiz/MineOptimiz/v1.20.1-Dev-buildtime.${{ steps.date.outputs.date }}.zip ./*
      
      - uses: actions/upload-artifact@v2
        with:
          name: v1.20.1-Dev-buildtime.${{ steps.date.outputs.date }}.zip
          path: /home/runner/work/MineOptimiz/MineOptimiz/v1.20.1-Dev-buildtime.${{ steps.date.outputs.date }}.zip
     
